### ISSUE TITLE
Crash on Forge Server 

### ISSUE THREAD

**Issue by OxiiGiin1** [Raik176/burnable-cobwebs#1]
[latest.log](https://github.com/user-attachments/files/17611388/latest.log)

**Comment by suerion** [comment]
Also on Fabric 1.21.1 on 0.16.9

https://mclo.gs/nwl7jD7

**Comment by Raik176** [comment]
Couldn't replicate this but should be fixed regardless as 0.1.7 doesn't use mixins anymore
